model_conf:
  0: 'Nafnet'
  1: 'Lakd-Net'
  2: 'UFP-Deblur'
  3: 'CGNet'
  4: 'CaptNet'
  5: 'Restormer'
  6: 'Loformer'
  7: 'SwinIR'
  8: 'FFT-Former'


xl:
  "Nafnet":
    param1: 1
    param2: 0
  "Lakd-Net":
    param1: 4
    param2: 2
  "UFP-Deblur":
    param1: 1
    param2: 0
  "CGNet":
    param1: 1
    param2: 0
  "CaptNet":
    param1: 4
    param2: 1
  "Restormer":
    param1: 4
    param2: 1
  "Loformer":
    param1: 1
    param2: 1
  "SwinIR":
    param1: 2
    param2: 2
  "FFT-Former":
    param1: 6
    param2: 0
  "conv-default":
    param1: 0
    param2: 0

xu:
  "Nafnet":
    param1: 28
    param2: 0
  "Lakd-Net":
    param1: 16
    param2: 4
  "UFP-Deblur":
    param1: 28
    param2: 0
  "CGNet":
    param1: 27
    param2: 0
  "CaptNet":
    param1: 16
    param2: 3
  "Restormer":
    param1: 8
    param2: 4
  "Loformer":
    param1: 9
    param2: 4
  "SwinIR":
    param1: 16
    param2: 16
  "FFT-Former":
    param1: 12
    param2: 0
  "conv-default":
    param1: 1
    param2: 0



